name: kodipay
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2  # For making HTTP requests (similar to Axios)
  provider: ^6.1.2  # For state management (similar to React Context)
  go_router: ^13.2.0  # For navigation (similar to React Navigation)
  shared_preferences: ^2.2.2
  local_auth: ^2.1.8
  intl: ^0.19.0
  socket_io_client: ^2.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - lib\assets\images\logo.webp