name: kodipay
description: A property management mobile application for landlords and tenants.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  go_router: ^10.0.0
  socket_io_client: ^2.0.3+1
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share_plus: ^7.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  local_auth: ^2.1.6
  fl_chart: ^0.66.2
  web_socket_channel: ^2.4.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
